# Generated by Django 5.1 on 2025-01-27 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_date_questions_problem_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='problem_count',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='submission_time',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user_id',
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('answer', models.TextField()),
                ('problem_count', models.IntegerField(default=0)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
