# Generated by Django 5.1 on 2025-01-28 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questions_date_remove_questions_problem_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('submission_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Submission Tracker',
                'verbose_name_plural': 'Submission Trackers',
                'unique_together': {('user_id', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
