# Generated by Django 5.1 on 2024-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_text', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('unique_phrase', models.CharField(default='', max_length=200)),
                ('mostFrequentWord', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
