# Generated by Django 5.1 on 2024-09-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquestion',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyquestion',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
