# Generated by Django 5.1 on 2025-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='img_id',
            field=models.CharField(default='default_id', max_length=255),
        ),
    ]
